import Joi from "joi";
import { PegawaiInterface } from "@/interfaces/pegawai.interface";

export const CreatePegawaiSchema = {
  body: Joi.object<PegawaiInterface>().keys({
    name: Joi.string().required().min(3),
    email: Joi.string().email().required(),
    phone_number: Joi.string().required().min(10),
    gender: Joi.string().required(),
    rek: Joi.string().min(8),
    date_of_birth: Joi.string().required(),
    place_of_birth: Joi.string().required(),
    religion: Joi.string().required(),
    married_status: Joi.string().required(),
    blood_type: Joi.string().required(),
    father_name: Joi.string().required(),
    mother_name: Joi.string().required(),
    province: Joi.string().required(),
    city: Joi.string().required(),
    district: Joi.string().required(),
    sub_district: Joi.string().required(),
    rt: Joi.string().required(),
    rw: Joi.string().required(),
    postal_code: Joi.string().required(),
    address: Joi.string().required(),
    picture: Joi.string(),
    bank_name: Joi.string().required(),
    bank_rekening: Joi.string().required(),
    bank_account: Joi.string().required(),
    job_status: Joi.string().required(),
    job_pic: Joi.string(),
    job_start_date: Joi.string().required(),
    job_end_date: Joi.string(),
  }),
};

export const UpdatePegawaiSchema = {
  params: Joi.object().keys({
    id: Joi.string().required(),
  }),
  body: Joi.object<PegawaiInterface>().keys({
    name: Joi.string().required().min(3),
    email: Joi.string().email().required(),
    phone_number: Joi.string().required().min(10),
    gender: Joi.string().required(),
    rek: Joi.string().min(8),
    date_of_birth: Joi.string().required(),
    place_of_birth: Joi.string().required(),
    religion: Joi.string().required(),
    married_status: Joi.string().required(),
    blood_type: Joi.string().required(),
    father_name: Joi.string().required(),
    mother_name: Joi.string().required(),
    province: Joi.string().required(),
    city: Joi.string().required(),
    district: Joi.string().required(),
    sub_district: Joi.string().required(),
    rt: Joi.string().required(),
    rw: Joi.string().required(),
    postal_code: Joi.string().required(),
    address: Joi.string().required(),
    picture: Joi.string(),
    bank_name: Joi.string().required(),
    bank_rekening: Joi.string().required(),
    bank_account: Joi.string().required(),
    job_status: Joi.string(),
    job_start_date: Joi.string().required(),
    job_end_date: Joi.string(),
  }),
};
